### PR TITLE
Fix #1613: Restore the two argument fcntl.open() method.

### LINKED ISSUE #1613: fcntl.open with two arguments is missing in 0.4.0-M2
I dusted off some two month code that was working in 0.4.0-SNAPSHOT pre M1 to
send to a colleague.  The code uses the quite commonly used idiom
of fcntl.open with two arguments.  

It looks like the recent (2121d12f6bccc4dbd23c4d9d676b1cadfcb27c6c) varargs change to fcntl causes the two argument form  to no longer work.     

I looked tor a/an *fcnt*lSuite to verify what I thought I was seeing and did not
find anything.  Mea culpa if I missed something obvious.

I believe, but have not tried out. That a/the solution is to declare the two 
argument form in fcntl.scala, That is, without the mode.
 
If I can replicate this, say by creating an fcntlSuite.scala, I will PR soonest.

### PR DESCRIPTION
**Pull request by LeeTibbert**
* This pull request was motivated by Issue #1613
    "fcntl.open with two arguments may be broken in 0.4.0-M2".
    It appeared the method stopped working in commit
    2121d12f6bccc4dbd23.

    Code calling the two argument method in SN 0.4.0-M2 fails to
    compile:
```
[error] Unspecified value parameter mode.
[error]     val fd = fcntl.open(fileName, fcntl.O_RDWR)
[error]                        ^
[error] one error found
[error] (tests/test:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Jun 2, 2019, 12:45:58 PM
```

    That issue is now fixed and a unit-test Suite created to
    detect its recurrence.

  * The current Pull Request makes minimal changes. The two
    argument form of the method restored and a redundant import
    is deleted. This is to isolate and highlight the operative
    change to aid review & acceptance.

    fcntl.scala will need future work to bring it into compliance with
    Posix/SingleUnix.

  * Only minimal tests were added in the new FcntlSuite.scala.
    These verify the current change and detect possible
    interference with the three argument version of open().

    Further improvement is invited and  left as an exercise for the
    Gentle Reader.

Documentation:

  * The standard changelog entry is requested.

Testing:

  * Built and tested ("test-all") in release-fast mode using sbt 1.2.8 on
    X86_64 only . All tests pass.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
Proactively rebased. Travis CI is all green.

**Review by sjrd — APPROVED** [review]

**Comment by ekrich** [comment]
I looked at this quite some time ago and didn't have time to review this recently due to vacation and travel. 

We let this go in using the old test suite vs JUnit.

Also, now we have added a test for POSIX which is running counter to prior practices and also is going to make it harder to separate tests so we can support Windows.

In the past we looked at the code as just bindings and didn't provide tests. This of course was when Denys was running the project. I guess his attitude was that the C works and if our binding doesn't it is either Scala Native or the binding is malformed. We hand code bindings but I guess there was a hope for good automated bindings at some point. Not sure how realistic that is but thought I'd throw this out there.

**Comment by LeeTibbert** [comment]
Eric,  thank you for the review and refreshing the rationale.  I think lack of tests is how the regression
fixed by the PR managed to slip in.  

Actually, I think there are two or three things which got fixed in a series of PRs on the same file.

**Comment by ekrich** [comment]
I don't disagree but there is no long term strategy for tests and ones for POSIX are most certainly going to be the first to be commented out if anyone attempts a Windows port.
