### ISSUE TITLE
tools/test doesn't work on master, with 2.12.13

### ISSUE THREAD

**Issue by sjrd** [scala-native/scala-native#2112]
It seems the CI is still running `tools/test` with 2.12.12, and in fact `tools/test` doesn't work anymore with 2.12.13, which is now the default in the build.

```
sbt:scala-native> tools/test
[info] compiling 2 Scala sources to /localhome/doeraene/projects/scala-native/testing-compiler/target/scala-2.12/classes ...
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala-2.12/scala/scalanative/compiler/CompatReporter.scala:3:8: object AbstractReporter is not a member of package scala.tools.nsc.reporters
[error] import scala.tools.nsc.reporters.AbstractReporter
[error]        ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala-2.12/scala/scalanative/compiler/CompatReporter.scala:6:51: not found: type AbstractReporter
[error] private[scalanative] trait CompatReporter extends AbstractReporter {
[error]                                                   ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala-2.12/scala/scalanative/compiler/CompatReporter.scala:7:49: not found: type Severity
[error]   def add(pos: Position, msg: String, severity: Severity): Unit
[error]                                                 ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala-2.12/scala/scalanative/compiler/CompatReporter.scala:9:62: not found: type Severity
[error]   override def display(pos: Position, msg: String, severity: Severity): Unit =
[error]                                                              ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala/scalanative/NIRCompiler.scala:59:60: not found: type Severity
[error]     override def add(pos: Position, msg: String, severity: Severity): Unit =
[error]                                                            ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala/scalanative/NIRCompiler.scala:61:14: not found: value ERROR
[error]         case ERROR => reportError(msg)
[error]              ^
[error] /localhome/doeraene/projects/scala-native/testing-compiler/src/main/scala/scalanative/NIRCompiler.scala:108:34: type mismatch;
[error]  found   : NIRCompiler.this.TestReporter
[error]  required: scala.tools.nsc.reporters.Reporter
[error]     new Global(command.settings, reporter)
[error]                                  ^
[error] 7 errors found
[error] (testingCompiler / Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Jan 14, 2021 12:45:46 PM
```

@WojciechMazur Could you have a look at that?

**Comment by WojciechMazur** [comment]
In 2.12.13 `AbstractReporter` was replaced with `FilteringReporter` used in 2.13.x. I'm preapering proper fix to allow also compiling against 2.12.12- versions
