### ISSUE TITLE
`sbt test` fails on subproject without any tests when it depends on module which is using `scalatests` for tests and `sbt-crossproject`

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#2483]
I'm using `scalatests` and it isn't implemented at all subproject in my main repository where I'm using scala-native. And have quite a complicated build. It includes `sbt-crossproject` and main code is builds for different paltforms and different scala version.

One of subproject is using 2.13 and haven't used any tests. But it depends on a project which uses (a lot of) tests.

Usually I run tests as `sbt +test` and after  updating from `0.4.0` to `0.4.2` I've discovered that this project had fails. It fails with symptoms:
1. `-out` binary consume 100% of CPU and never ends;
2. It fails when sbt tries to run tests like that:
```
[error] Fatal signal 11 caught
[error]   at scala.scalanative.testinterface.signalhandling.SignalConfig$$$Lambda$1.(Unknown Source)
[error]   at <none>._sigtramp(Unknown Source)
[error]   at <none>._ZN9libunwind22CompactUnwinder_x86_64INS_17LocalAddressSpaceEE32stepWithCompactEncodingFramelessEjyRS1_RNS_16Registers_x86_64Eb(Unknown Source)
[error]   at <none>._ZN9libunwind12UnwindCursorINS_17LocalAddressSpaceENS_16Registers_x86_64EE4stepEv(Unknown Source)
[error]   at java.lang.StackTrace$.currentStackTrace(Unknown Source)
```

(2) doesn't produce any issues and sbt continue as is. From antoher hand (1) exists after sbt is crashed  and I've discovered this bug because my laptop was very noisy when it just rests on the table and should do nothing.

The simplest reproducer is:
```
import sbtcrossproject.CrossPlugin.autoImport.crossProject

ThisBuild / scalaVersion := "2.12.15"
crossScalaVersions := Seq()

lazy val bugCore = crossProject(NativePlatform)
  .in(file("bugCore"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % "3.2.10" % Test,
    )
  )

lazy val bug = crossProject(NativePlatform)
  .in(file("bug"))
  .dependsOn(bugCore)
  .nativeSettings(
    nativeMode := "release-fast",
    nativeLTO := "thin"
  )
```

anyway, removing / commenting  one of `nativeMode` or `nativeLTO` overstep an issue. Switching to scala-2.13 doesn't fix an issue anyway. Nor switching to `2.12.13` or `2.12.13`.

Let me assume that `plugins.sbt` contains: 
```
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.1.0")

val scalaNativeJSVersion =
  Option(System.getenv("SCALANATIVE_VERSION")).getOrElse("0.4.2")

addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % scalaNativeJSVersion)
```
and I've fixed used scalatest as:
```
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest_native0.4" % "3.2.10" % Test,
    )
```
that allows me to run simple test to determine when it started to fail:
 - `0.4.0` works fine
 - `0.4.1` fails

That leads to `git bisect`:
```
# bad: [087e2a2dff3b0028367cb0949bae2641a9f8947e] Release 0.4.1 (#2414)
# good: [f2c2ca45ba7589ee81b78ce182b63e0bc73b45ec] Release 0.4.0 (#2105)
git bisect start 'v0.4.1' 'v0.4.0'
# good: [7997e294c3d29aeb4c32d8b91b8e91062f667e1f] Fix #2277: Remove memset and cleanup (#2308)
git bisect good 7997e294c3d29aeb4c32d8b91b8e91062f667e1f
# bad: [6886f685231b729821c3089fd30664ce79a8fa03] Add Scala 2.12.15 to the build definition (#2365)
git bisect bad 6886f685231b729821c3089fd30664ce79a8fa03
# good: [28eaa4288cd7aa97f983f663d89702741bc9f7a0] Ignore no longer existing objects when inheriting Interflow state (#2344)
git bisect good 28eaa4288cd7aa97f983f663d89702741bc9f7a0
# bad: [e5b673b8ce1ee47e0fe19904cb95d22b8baacde8] Provide stubs for POSIX specific implementation on Windows (#2345)
git bisect bad e5b673b8ce1ee47e0fe19904cb95d22b8baacde8
# bad: [1fff231a65028205f14ceaef2a97cd5ee0cad56b] Update and enhance Readme (#2350)
git bisect bad 1fff231a65028205f14ceaef2a97cd5ee0cad56b
# good: [4e0de6f86b7846bb6a0d7e328b770f9071c2a73a] Fix #2313: Defect in j.n.InetAddress#createIPStringFromByteArray (#2348)
git bisect good 4e0de6f86b7846bb6a0d7e328b770f9071c2a73a
# bad: [28345bb1f6161690dc23ce6d26feba529781ff67] Add a default signal handler to `TestMain` (#2338)
git bisect bad 28345bb1f6161690dc23ce6d26feba529781ff67
# good: [dbc1c1b9087f6ba505128cad9c29a252e062a123] if Windows, append .exe to binaryName in discover(), to support mingw64 and cygwin compilers (#2349)
git bisect good dbc1c1b9087f6ba505128cad9c29a252e062a123
# first bad commit: [28345bb1f6161690dc23ce6d26feba529781ff67] Add a default signal handler to `TestMain` (#2338)
```
That leads to a root cause of this issue: 28345bb1f6161690dc23ce6d26feba529781ff67

**Comment by catap** [comment]
Main code includes some C-level wrapper for uv. As soon as I've switched sub-project to `nativeLTO := "none"` I discovered an issue belowe:
```
[error] /usr/bin/ld: [...]/native/target/scala-2.13/native/native-code-classes-0/scala-native/libuv-addons.c.o: in function `uv_write_single':
[error] libuv-addons.c:(.text+0x68): undefined reference to `uv_buf_init'
[error] /usr/bin/ld: libuv-addons.c:(.text+0x87): undefined reference to `uv_write'
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyway, it builds fine on macOS with `nativeLTO := "none"`. But Linux via GItHub CI fails on this issue.

**Comment by WojciechMazur** [comment]
Thank you for reporting this issue, I'll try to take a look at I it next week. The difference in behaviour between MacOS and Linux is also very strange and should not happen

**Comment by catap** [comment]
@WojciechMazur I feel that I'm describing symptoms.
